---
title: "R Notebook"
output: html_notebook
---

שינוי בהרכב הגילאים בישראל במהלך שנות האלפיים

```{r}

library(pacman)
p_load(tidyverse, openxlsx, readxl, utf8, ggplot2, scales, magrittr)
p_load(ggplot2, ggridges, ggpubr, scales, cowplot,viridisLite, viridis, RColorBrewer,ggsci,ggthemes,patchwork,scales )


getwd()

```

דבר ראשון, צריך להפריד בין יהודים לערבים. היה טוב אם הייתי יכול להפריד גם בין עולים מרוסיה לבין שאר האוכלוסייה, אבל זה קשה לביצוע במסגרת הדאטה שלי

בגלל ההבדל בגודל האוכלוסיות, טוב להראות גם את המספרים המוחלטים וגם את האחוזים

```{r}

p_population_grouop_num <- population_2000_2020_int %>%
filter( population_group %in% c("arab_total", "jews_and_others_total"), year == 2020  ) %>%
ggplot(aes(age, number, color = population_group)) +
         geom_path(size = 2)+
  theme_bw() +
#    scale_color_brewer(type = "qual" ,palette = "Set1")+
  scale_colour_manual(values = c("#4DAF4A", "#377EB8" ))+ #השתמשתי בהגדרה ידנית מתוך הפלטה כדי שהצבעים יתאימו אינטואיטיבית כחול יהודים וירוק ערבים. היה טוב אם הייתה דרך לדלג על צבע בפלטה אבל לא מצאתי כזאת ולכן הגדרתי ידנית
  theme(panel.grid.minor = element_blank())  +
  scale_y_continuous(n.breaks = 8, labels = label_comma())  + 
scale_x_continuous(n.breaks = 8) 

p_population_grouop_prc <- population_2000_2020_int %>%
filter( population_group %in% c("arab_total", "jews_and_others_total"), year == 2020  ) %>%
ggplot(aes(age, prc_of_group, color = population_group)) +
         geom_path(size = 1)+
  theme_bw() +
  scale_colour_manual(values = c("#4DAF4A", "#377EB8" ))+
  theme(panel.grid.minor = element_blank())  +
  scale_y_continuous(n.breaks = 8, labels = label_comma())  + 
scale_x_continuous(n.breaks = 8) 

p_population_grouop_area <- population_2000_2020_int %>%
    filter( population_group %in% c("arab_total", "jews_and_others_total"), year == 2020  ) %>% group_by( age) %>%
     summarise(population_group = population_group,
               age = age,
               percentage = number/ sum(number)) %>% ungroup() %>%
     ggplot(aes(age, percentage, fill = population_group)) +
     geom_area( color = "black")  +
     theme_bw() +
     scale_fill_manual(values = c("#4DAF4A", "#377EB8" ))+
     theme(panel.grid.minor = element_blank())  +
     scale_y_continuous(n.breaks = 8, labels = label_comma())  + 
     scale_x_continuous(n.breaks = 8) 

#plot_grid(p_population_grouop_num,p_population_grouop_prc)
p_population_grouop_num
p_population_grouop_prc
p_population_grouop_area


```
